POST http://localhost:8765/auth/oauth/token
Authorization: Basic myappname123 myappscret123
Content-Type: application/x-www-form-urlencoded

username = 222222222 &
password = 123 &
grant_type = password

### POST
POST http://localhost:8765/configuracao/permissoes

### GET request with a header
GET http://localhost:8765/user-api/usuarios/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzE3MDQ4MjYsInVzZXJfbmFtZSI6IjIyMjIyMjIyMiIsImF1dGhvcml0aWVzIjpbIkNMSUVOVEUiXSwianRpIjoiODFmYTJjN2QtM2JhYS00MjAyLWFkY2QtODNlNjEyZjJiMmRmIiwiY2xpZW50X2lkIjoibXlhcHBuYW1lMTIzIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.DzGk8W2NWmRFZyhwXkLul3ppAa-8Vfk1t7TKibjHD7U

### GET request with a header
GET http://localhost:8765/user-api/usuarios/cpf/1111111111
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzE3MDQ4MjYsInVzZXJfbmFtZSI6IjIyMjIyMjIyMiIsImF1dGhvcml0aWVzIjpbIkNMSUVOVEUiXSwianRpIjoiODFmYTJjN2QtM2JhYS00MjAyLWFkY2QtODNlNjEyZjJiMmRmIiwiY2xpZW50X2lkIjoibXlhcHBuYW1lMTIzIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.DzGk8W2NWmRFZyhwXkLul3ppAa-8Vfk1t7TKibjHD7U

### Send POST request with json body
POST http://localhost:8765/user-api/usuarios
Content-Type: application/json

{
  "nome": "Renan Duarte",
  "email": "renan3@gmail.com",
  "login": "renan.duarte",
  "cpf": "3333333",
  "senha": "123"
}
