spring.application.name=gateway
server.port=8765

oauth.client.name=myappname123
oauth.client.secret=myappscret123
jwt.secret=CHAVE_SECRETA

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

token-permissions=CHAVE-INTEGRACAO

# Configuração de Timeout
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=60000
ribbon.ConnectTimeout=10000
ribbon.ReadTimeout=20000

# Configuração Zuul para rotear tudo da aplicação pelo gateway
zuul.routes.user.service-id=user-api
zuul.routes.user.path=/user-api/**

zuul.routes.estoque.service-id=estoque-api
zuul.routes.estoque.path=/estoque-api/**

zuul.routes.oauth.service-id=auth
zuul.routes.oauth.path=/auth/**
zuul.routes.oauth.sensitive-headers=Cookie,Set-Cookie
