spring.application.name=auth
jwt.secret=CHAVE_SECRETA
oauth.client.name=myappname123
oauth.client.secret=myappscret123

server.port=${PORT:0}

#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

